# Generated by Django 4.2.7 on 2023-12-02 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('button_color', models.CharField(default='lightgray', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(upload_to='trained_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlp.modelname')),
            ],
        ),
    ]
